### ISSUE TITLE
Couldn't find any clusters on your configuration file

### ISSUE THREAD

**Issue by eilonk** [tchiotludo/kafkahq#184]
Hi, I'm trying to configure kafkahq for the first time
I am using helm to deploy it on kubernetes, but when i try to access it, i get the following error:

> {"message":"Internal Server Error: Couldn't find any clusters on your configuration file, please ensure that the configuration file is loaded correctly","logref":{"empty":true,"present":false},"path":{"empty":true,"present":false}}

the kafka itself is working correctly and i only changed "cluster-name" from my original one,
when I deploy it, I get no errors. But when I try to login through 127.0.0.1:8080 i get the error message

my configuration file looks like this:
```yaml
image:
  repository: tchiotludo/kafkahq
  tag: latest
  annotations: {}
  extraEnv: {}

secrets: |
  kafkahq:
    secrets:
      cluster-name:
        properties:
          bootstrap.servers: "strimzi-kafka-control-kafka-bootstrap.cluster-name:9092"
        connect:
          url: ""

kafkahq:
  connections: 
    cluster-name:
      properties:
              bootstrap.servers: "strimzi-kafka-control-kafka-bootstrap.cluster-name:9092"

service:
  enabled: true
  type: ClusterIP
  port: 80
  annotations: {}

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}
```

I'm not really sure why it has problem locating my cluster, and would love to get some insights:
1. Bootstrap servers - should i write my main bootstrap address only? 2 ports are open on this address and i saw some conflicts online wether i should add the kafka-control servers as well?
2. is anything else missing/wrong? 

Thanks in advance for any help :)

**Comment by tchiotludo** [comment]
Hi, 

Can you edit your issue with formatted yaml ? 
It's impossible to help you without indentation 

Thanks

**Comment by eilonk** [comment]
> Hi,
> 
> Can you edit your issue with formatted yaml ?
> It's impossible to help you without indentation
> 
> Thanks

Hi, i changed it - it's my first issue sorry..

**Comment by tchiotludo** [comment]
I've a better view now. 

There is a bug on helm that i corrected now : 

here is a minimal working examples : 
```yaml
secrets: |
  kafkahq:
    connections:
      cluster-name:
        properties:
          bootstrap.servers: "strimzi-kafka-control-kafka-bootstrap.cluster-name:9092"
        connect:
          url: ""
```
no need to duplicated `bootstrap.servers` on `configuration` & `secrets`
The `bootstrap.servers` need to be at least one server on your cluster (can be many seperated by `,`)

**Comment by eilonk** [comment]
i still get the error 
i tried editing the bootstrap.servers like you said and changed it to the fqdn name
(strimzi-kafka-control-kafka-bootstrap.cluster-name.svc.cluster.local)
and this doesn't seem to work either

**Comment by tchiotludo** [comment]
can you connect on the pods and see if there is a file on `/app/application.yml` or `/app/application-secrets.yml` with the configuration you provide ? 
You can put in configuration or secrets, it's have not impact, both are loaded, but configuration is a simple configmap and credential are in clear text

**Comment by eilonk** [comment]
yes, the file exists and has the configurations inside

**Comment by tchiotludo** [comment]
can you go on `/env` url please, this will output the configuration that KafkaHQ see please ?

**Comment by eilonk** [comment]
what am i looking for here?
there isn't a /env path in the pod (no such file or directory)
when looking at env (variables) i do see it set some for the kafkahq:
(i erased the address but it appears where it says x.x.x.x - same one for all of them)
```
KAFKAHQ_0_1_0_PORT=tcp://x.x.x.x:80
KAFKAHQ_0_1_0_SERVICE_PORT_HTTP=80
KAFKAHQ_0_1_0_SERVICE_PORT=80
KAFKAHQ_0_1_0_PORT_80_TCP_PORT=80
KAFKAHQ_0_1_0_PORT_80_TCP_ADDR=x.x.x.x
KAFKAHQ_0_1_0_PORT_80_TCP=tcp://x.x.x.x:80
KAFKAHQ_0_1_0_PORT_80_TCP_PROTO=tcp
KAFKAHQ_0_1_0_SERVICE_HOST=x.x.x.x
```

**Comment by tchiotludo** [comment]
Sorry' I'm on http like http://pods:8080/env

**Comment by eilonk** [comment]
oh no worries
with port forwarding i get the same error output

when i try to access it directly it doesn't even load anything, so i checked if the pod is ok
i got this warning
Readiness probe failed: HTTP probe failed with statuscode: 500
is there any network configuration i left out or something needed?

**Comment by tchiotludo** [comment]
really strange ... 
The readiness check is always working, no matter the configuration. 

the kubectl logs don't give you any information ?

**Comment by eilonk** [comment]
super weird to me too.. everything seems fine other than that
the logs only tell me that the same error as put before and nothing new
are there any requirements that my server might be exceeding?

**Comment by tchiotludo** [comment]
I don't think so ... 
Really hard to help blindness for me ... 

The things I really need to debug your case is the files on /app/*.yml.
And the curl `http://localhost:8080/env`

Without the 2, I can't help you ... sorry

**Comment by eilonk** [comment]
if there's anything else tell me, thanks for helping out

**Event from pod logs:**
``` WARN  pGroup-1-2 org.kafkahq.log.access     [Date: 2020-01-14T14:17:59.258649Z] [Duration: 3 ms] [Url: GET /health HTTP/1.1] [Status: 500] [Ip: x.x.x.x] [Length: 231] [Port: 8080] ```

**curl output: (same as before)**
``` {"message":"Internal Server Error: Couldn't find any clusters on your configuration file, please ensure that the configuration file is loaded correctly","logref":{"empty":true,"present":false},"path":{"empty":true,"present":false}} ```

**content of application-secrets.yml: (only yml file under /app)**
``` kafkahq:
  cluster-name:
    properties:
      bootstrap.servers: "strimzi-kafka-control-kafka-bootstrap.cluster-name.svc.cluster.local:9092"
    connect:
      url: "http://x.x.x.x:9094" ```

**Comment by eilonk** [comment]
will other logs help? java log trace f.e?

**Comment by tchiotludo** [comment]
Things is see : 
Your yaml is wrong, `kafkahq:` root is missing : 

```yaml
kafkahq:
  cluster-name:
    properties:
      bootstrap.servers: "strimzi-kafka-control-kafka-bootstrap.cluster-name.svc.cluster.local:9092"
    connect:
      url: "http://x.x.x.x:9094" 
```

The curl `curl http://localhost:8080/env` can't display this error, since this endpoint don't try to connect to kafka, must be this kind of output : 
```json
{
  "activeEnvironments": [
    "dev"
  ],
  "packages": [
    "org.kafkahq"
  ],
  "propertySources": [
    {
      "........................."
    } 
  ]
}
```

I forgot this one is disabled by default, you need to add this to your configuration files : 
```
endpoints:
    env:
        enabled: true
        sensitive: true
```

Hope it can help

**Comment by eilonk** [comment]
Hi, thanks for the extra help
i added everything you listed but i still get the errors in the logs (cant find my cluster)
i looked at the application.yml file to see if it gets the values after deployment but the file doesn't look that affected, hope this could shed some light to why it isn't working:
```
micronaut:
  application:
    name: kafkahq
  io:
    watch:
      paths: src/main
      restart: false # enabled dev server with env vars MICRONAUT_IO_WATCH_RESTART=true
  router:
    static-resources:
      static:
        paths: classpath:static
        mapping: "${kafkahq.server.base-path:}/static/**"
  security:
    enabled: true
    endpoints:
      login:
        enabled: true
        path: "${kafkahq.server.base-path:}/login"
      logout:
        enabled: true
        path: "${kafkahq.server.base-path:}/logout"
        get-allowed: true
    session:
      enabled: true
      login-success-target-url: "${kafkahq.server.base-path:}/"
      logout-target-url: "${kafkahq.server.base-path:}/"
      forbidden-target-url: "${kafkahq.server.base-path:}/login/forbidden"
      unauthorized-target-url: "${kafkahq.server.base-path:}/login/unauthorized"
      login-failure-target-url: "${kafkahq.server.base-path:}/login/failed"
    intercept-url-map:
      - pattern: "${kafkahq.server.base-path:}/static/**"
        access: "isAnonymous()"
  caches:
    kafka-wrapper:
      record-stats: true
      expire-after-write: 0s

endpoints:
  all:
    path: "${kafkahq.server.base-path:}"
  health:
    enabled: true
    sensitive: false
    details-visible: anonymous
  info:
    enabled: true
    sensitive: false
  metrics:
    enabled: true
    sensitive: false
    export:
      prometheus:
        enabled: true
        step: PT1M
        descriptions: true
  prometheus:
    enabled: true
    sensitive: false
  caches:
    enabled: true
    sensitive: false

jackson:
  module-scan: false

kafkahq:
  server:
    base-path: ""
    access-log:
      enabled: true
      name: org.kafkahq.log.access
      format: "[Date: {}] [Duration: {} ms] [Url: {} {} {}] [Status: {}] [Ip: {}] [Length: {}] [Port: {}]"

  clients-defaults:
    consumer:
      properties:
        max.poll.records: 50
        isolation.level: read_committed
        group.id: KafkaHQ
        enable.auto.commit: "false"
        default.api.timeout.ms: 15000

  pagination:
    page-size: 25
    threads: 16

  topic:
    default-view: HIDE_INTERNAL
    replication: 1
    retention: 86400000
    partition: 1
    internal-regexps:
      - "^_.*$"
      - "^.*_schemas$"
      - "^.*connect-config$"
      - "^.*connect-offsets$1"
      - "^.*connect-status$"
    stream-regexps:
      - "^.*-changelog$"
      - "^.*-repartition$"
      - "^.*-rekey$"
    skip-consumer-groups: false

  topic-data:
    sort: OLDEST
    size: 50
    poll-timeout: 1000

  security:
    default-groups:
      - admin
    groups:
      admin:
        roles:
        - topic/read
        - topic/insert
        - topic/delete
        - topic/config/update
        - node/read
        - node/config/update
        - topic/data/read
        - topic/data/insert
        - topic/data/delete
        - group/read
        - group/delete
        - group/offsets/update
        - registry/read
        - registry/insert
        - registry/update
        - registry/delete
        - registry/version/delete
        - acls/read
        - connect/read
        - connect/insert
        - connect/update
        - connect/delete
        - connect/state/update
      reader:
        roles:
          - topic/read
          - node/read
          - topic/data/read
          - group/read
          - registry/read
          - acls/read
          - connect/read
```

when i try the curl it still displays the same internal server error.
i think the problem is only that it can't find the cluster, but i don't really understand why

**Comment by eilonk** [comment]
I wrote the configuration file again and it worked.

i think the problem was the double use of configuration and secrets that both required similar values.
if someone is looking at this with the same problem - make sure the configuration can accept strings (use |) and that your yaml is accurate

thanks for the help, @tchiotludo !
